dist: xenial

language: node_js

node_js:
  - '10'

git:
  depth: 1

before_install:
 - npm i -g npm@6.5.0

# Use npm ci to ensure a clean install of dependencies
install:
 - npm ci
 - npm i -g codeclimate-test-reporter

# Keep the npm cache around to speed up installs
cache: npm

script:
 - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false